### ISSUE TITLE
Could not find a suitable provider for s3 - first start vagrant virtualbox 

### ISSUE THREAD

**Issue by tuxinaut** [malnick/puppet-s3#3]
I've the problem that if I start the vagrant virtualbox the first time I get always the output below that there is **no suitable provider for s3**. If I trigger the provision a second time it works.

Puppet 3.4.3
Vagrant 1.7.2

```
==> default: Debug: Prefetching gem resources for package
==> default: Debug: Executing '/usr/bin/gem list --local'
==> default: Debug: Executing '/usr/bin/gem list --local aws-sdk$'
==> default: Debug: Executing '/usr/bin/gem install --no-rdoc --no-ri aws-sdk'
==> default: Notice: /Stage[main]/S3/Package[aws-sdk]/ensure: created
==> default: Debug: /Stage[main]/S3/Package[aws-sdk]: The container Class[S3] will propagate my refresh event
...
==> default: Debug: Failed to load library 'aws-sdk' for feature 'awssdk'
==> default: Debug: Puppet::Type::S3::ProviderS3: feature awssdk is missing
...
==> default: Error: Could not find a suitable provider for s3
```

**Comment by mashurex** [comment]
I'm seeing the same issue with `Vagrant 1.7.4`, `Puppet 3.4.3` with OS X host OS and Ubuntu 14.04x64 guest OS.

It appears that the aws-sdk gem needs to be installed before Puppet is initialized. I have worked around this by installing the gem in the `Vagrantfile` with an inline shell provisioner before the Puppet provisioner like so:

```
config.vm.provision :shell, :inline => "gem install aws-sdk"
```

I don't know if it's possible, but it seems like getting Puppet to re-detect available gems after it has started would be the nice, 'Puppet only' way to fix it.

**Comment by tuxinaut** [comment]
You haven't to install `aws-sdk` manually simple **include** this puppet module should be enough. See also [init.pp](https://github.com/malnick/puppet-s3/blob/production/manifests/init.pp). Additionally the module has code to detect multiple times if the `aws-sdk` installed.
